b-assn5: b-assn5.c functions.c functions.h Makefile
	gcc  -o b-assn5 b-assn5.c functions.c

main: main.c functions.c functions2.c functions.h getReady.c firstcome.c Makefile arrivals.c clock_tick.c selectReady.c
	gcc -o main main.c functions.c functions2.c functions.h getReady.c firstcome.c arrivals.c clock_tick.c selectReady.c

clean: b-assn5
	rm -rf
